image: docker:latest

stages:
  - build

variables:
  CONTAINER_LOCAL_IMAGE: rs_ftp_worker
  CONTAINER_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE_NAME: mediaio/rs_ftp_worker

before_script:
   - git submodule sync --recursive
   - git submodule update --init --recursive

build:
  stage: build
  script:
    - export IMAGE_TAG=`git describe --always --tags --first-parent`
    - docker build --build-arg IMAGE_TAG=IMAGE_TAG --build-arg VERSION=IMAGE_TAG -t $CONTAINER_LOCAL_IMAGE .
    - docker login -u maarnaud -p $REGISTRY_PASSWORD $CONTAINER_REGISTRY
    - docker tag $CONTAINER_LOCAL_IMAGE $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:$IMAGE_TAG
    - docker push $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:$IMAGE_TAG
    - echo $CONTAINER_REGISTRY/$CONTAINER_IMAGE_NAME:$IMAGE_TAG
  tags:
    - mediaio
