[package]
name = "tranfer_worker"
version = "0.1.0"
authors = [
  "Valentin Noel <valentin.noel@media-io.com>",
  "Marc-Antoine Arnaud <maarnaud@media-io.com>",
]
edition = "2018"

[dependencies]
amqp_worker = { version = "0.5.4" }
ftp = { version = "3.0.1", features = ["secure"] }
futures = "0.1.25"
futures-util = "0.2"
log = "0.4.5"
reqwest = "0.9.5"
rusoto_core = "0.40.0"
rusoto_credential = "0.40.0"
rusoto_s3 = "0.40.0"
simple_logger = "1.0.1"
tokio = "0.1"
tokio-io = "0.1"
