[package]
name = "ftp_worker"
version = "0.1.0"
authors = [
  "Valentin Noel <valentin.noel@media-io.com>",
  "Marc-Antoine Arnaud <maarnaud@media-io.com>",
]
edition = "2018"

[dependencies]
amqp_worker = "0.4.3"
ftp = { version = "3.0.1", features = ["secure"] }
log = "0.4.5"
simple_logger = "1.0.1"
